---
- name: Установка Java
  apt:
    name: openjdk-17-jre-headless
    state: present
    update_cache: yes

- name: Копирование Elasticsearch deb
  copy:
    src: ../../elasticsearch-8.12.0-amd64.deb
    dest: /tmp/elasticsearch.deb

- name: Установка Elasticsearch
  apt:
    deb: /tmp/elasticsearch.deb
    state: present

- name: Настройка Elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: restart elasticsearch

- name: Запуск Elasticsearch
  systemd:
    name: elasticsearch
    state: started
    enabled: yes
